import { Geist, Geist_Mono } from "next/font/google";
import './global.scss';
import styles from "@/app/(page)/auth/login/page.module.scss";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
      {children}
      </body>
    </html>
  );
}
